.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-contract 1  StarForge "User Manual"
.SH NAME
starforge\-contract \- Contract operations (invoke, inspect, etc.)
.SH SYNOPSIS
\fBstarforge\-contract\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Contract operations (invoke, inspect, etc.)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
