.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge 1  StarForge "User Manual"
.SH NAME
starforge
.SH SYNOPSIS
\fBstarforge\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
starforge\-wallet(1)
.TP
starforge\-new(1)
.TP
starforge\-contract(1)
.TP
starforge\-inspect(1)
.TP
starforge\-deploy(1)
.TP
starforge\-info(1)
.TP
starforge\-tx(1)
.TP
starforge\-network(1)
.TP
starforge\-completions(1)
.TP
starforge\-shell(1)
.TP
starforge\-monitor(1)
.TP
starforge\-tutorial(1)
.TP
starforge\-benchmark(1)
.TP
starforge\-test(1)
.TP
starforge\-gas(1)
.TP
starforge\-plugin(1)
.TP
starforge\-template(1)
.TP
starforge\-upgrade(1)
.TP
starforge\-man(1)
.TP
starforge\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.1.0
