.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-inspect 1  StarForge "User Manual"
.SH NAME
starforge\-inspect \- Deep contract storage inspection (state, key, storage)
.SH SYNOPSIS
\fBstarforge\-inspect\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Deep contract storage inspection (state, key, storage)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
