.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-man 1  StarForge "User Manual"
.SH NAME
starforge\-man \- Generate or install man pages
.SH SYNOPSIS
\fBstarforge\-man\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Generate or install man pages
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
