.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-debug 1  StarForge "User Manual"
.SH NAME
starforge\-debug \- Debug Soroban contracts with breakpoints, stepping, and inspection
.SH SYNOPSIS
\fBstarforge\-debug\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Debug Soroban contracts with breakpoints, stepping, and inspection
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
