.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-perf 1  StarForge "User Manual"
.SH NAME
starforge\-perf \- Contract performance monitoring and metrics dashboard
.SH SYNOPSIS
\fBstarforge\-perf\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Contract performance monitoring and metrics dashboard
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
